# Generated by Django 3.2.25 on 2026-08-06 02:07

from django.db import migrations, models
import url_shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the URL', max_length=100, null=True)),
                ('original_url', models.URLField(max_length=2000)),
                ('short_code', models.CharField(db_index=True, default=url_shortener.models.generate_short_code, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
        ),
    ]
