# Generated by Django 2.1.11 on 2020-07-14 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import interview_exp.models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), interview_exp.models.max_value_current_year])),
                ('job_Profile', models.CharField(max_length=100)),
                ('role_Type', models.CharField(choices=[('Internship', 'Internship'), ('Full Time', 'Full Time')], max_length=50)),
                ('no_of_Rounds', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('interview_Questions', markdownx.models.MarkdownxField()),
                ('total_Compensation', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_Status', models.CharField(choices=[('Approved', 'Approved'), ('Review Pending', 'Review Pending'), ('Changes Requested', 'Changes Requested')], default='Review Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'db_table': 'experiences',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview_exp.Experiences')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Revisions',
                'db_table': 'revisions',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
