# Generated by Django 3.2.25 on 2026-08-05 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('college', models.CharField(default='National Institute of Technology, Durgapur', max_length=200)),
                ('batch', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dept', models.CharField(blank=True, db_index=True, max_length=100)),
                ('codeforces_handle', models.CharField(blank=True, db_index=True, max_length=100)),
                ('codeforces_rating', models.IntegerField(db_index=True, default=0)),
                ('codeforces_max_rating', models.IntegerField(default=0)),
                ('codeforces_rank', models.CharField(blank=True, max_length=50)),
                ('codechef_handle', models.CharField(blank=True, db_index=True, max_length=100)),
                ('codechef_rating', models.IntegerField(db_index=True, default=0)),
                ('codechef_stars', models.CharField(blank=True, max_length=20)),
                ('codechef_global_rank', models.IntegerField(blank=True, null=True)),
                ('leetcode_handle', models.CharField(blank=True, max_length=100)),
                ('leetcode_rating', models.IntegerField(db_index=True, default=0)),
                ('leetcode_solved', models.IntegerField(default=0)),
                ('codolio_handle', models.CharField(blank=True, max_length=100)),
                ('codolio_cscore', models.FloatField(db_index=True, default=0.0)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CP Profile',
                'verbose_name_plural': 'CP Profiles',
                'ordering': ['-codeforces_rating', '-codechef_rating'],
            },
        ),
    ]
