# Generated by Django 3.2.25 on 2026-08-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpprofile',
            name='codechef_contests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpprofile',
            name='codeforces_contests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpprofile',
            name='codeforces_solved',
            field=models.IntegerField(default=0),
        ),
    ]
