# Generated by Django 3.2.25 on 2026-08-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20260806_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpprofile',
            name='codechef_is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='cpprofile',
            name='codeforces_is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
