# Generated by Django 2.0.6 on 2019-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_of_graduation', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'members',
                'managed': True,
            },
        ),
    ]
