# Generated by Django 2.1.3 on 2018-12-16 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0003_auto_20181216_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tag',
            field=models.CharField(blank=True, default='math', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recursion_website.Questions'),
            preserve_default=False,
        ),
    ]
