# Generated by Django 2.1.3 on 2018-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0004_auto_20181216_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
