# Generated by Django 2.1.3 on 2018-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0008_auto_20181216_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
