# Generated by Django 2.1.3 on 2018-12-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0011_auto_20181216_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
    ]
