# Generated by Django 2.1.3 on 2018-12-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0013_auto_20181221_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taggings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
