# Generated by Django 2.1.3 on 2018-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0014_auto_20181229_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
