# Generated by Django 2.1.3 on 2018-12-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='visibility',
            field=models.BooleanField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
