# Generated by Django 2.1.5 on 2019-01-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image_url',
        ),
    ]
