# Generated by Django 2.1.5 on 2019-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
