# Generated by Django 2.1.5 on 2019-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0002_remove_events_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
