# Generated by Django 2.1.5 on 2019-03-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0002_auto_20190301_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
