# Generated by Django 2.1.3 on 2018-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0002_auto_20181215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
