# Generated by Django 2.1.5 on 2019-01-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0003_events_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
