# Generated by Django 2.1.3 on 2018-12-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0005_auto_20181216_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tag',
        ),
    ]
