# Generated by Django 2.1.3 on 2018-12-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0010_auto_20181216_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taggings',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursion_website.Questions'),
        ),
        migrations.AlterField(
            model_name='taggings',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursion_website.Tags'),
        ),
        migrations.AlterField(
            model_name='taggings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
