# Generated by Django 2.1.3 on 2018-12-20 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0012_auto_20181220_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'managed': True, 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True, 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='follows',
            options={'managed': True, 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': True, 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='taggings',
            options={'managed': True, 'verbose_name_plural': 'Taggings'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': True, 'verbose_name_plural': ' Tags'},
        ),
        migrations.AlterModelOptions(
            name='upvotes',
            options={'managed': True, 'verbose_name_plural': 'Upvotes'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taggings',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tags',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
