# Generated by Django 2.1.3 on 2018-12-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0015_auto_20181229_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answered',
        ),
    ]
