# Generated by Django 2.1.3 on 2018-12-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0017_auto_20181231_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='upvotes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
