# Generated by Django 2.1.3 on 2019-01-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursion_website', '0018_auto_20181231_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': True, 'ordering': ['created_at'], 'verbose_name_plural': 'Questions'},
        ),
    ]
