# Generated by Django 2.1.11 on 2020-10-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('upload', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('Number', models.PositiveIntegerField(default='', primary_key=True, serialize=False)),
                ('Level_title', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(blank=True, default='', max_length=200)),
                ('url_link1', models.URLField(blank=True)),
                ('link2', models.CharField(blank=True, default='', max_length=200)),
                ('url_link2', models.URLField(blank=True)),
                ('link3', models.CharField(blank=True, default='', max_length=200)),
                ('url_link3', models.URLField(blank=True)),
                ('link4', models.CharField(blank=True, default='', max_length=200)),
                ('url_link4', models.URLField(blank=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.File')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes_topic', models.CharField(blank=True, default='', max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('Image', models.ImageField(blank=True, upload_to='')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Level')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic', models.CharField(blank=True, max_length=200)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_title', models.CharField(blank=True, default='', max_length=200)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Level')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Topic'),
        ),
        migrations.AddField(
            model_name='note',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.SubTopic'),
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Topic'),
        ),
        migrations.AddField(
            model_name='file',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Level'),
        ),
        migrations.AddField(
            model_name='file',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.SubTopic'),
        ),
        migrations.AddField(
            model_name='file',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='getting_started.Topic'),
        ),
    ]
