# Generated by Django 2.1.11 on 2020-07-22 14:35

import django.core.validators
from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('batch_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2016), django.core.validators.MaxValueValidator(2050)])),
                ('url_Facebook', models.URLField()),
                ('url_LinkedIn', models.URLField()),
                ('mobile', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to=team.models.content_file_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
                'db_table': 'members',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
